### ISSUE TITLE
Yard

### ISSUE THREAD

**Issue by stevanwilson** [stevanwilson/UnitConverter#7]
I couldn't figure it out while I was looking, but when you switch to yard, it switches it back automatically to meter. If anyone can figure out why its doing this that would be awesome.

**Comment by Hydroplane72** [comment]
I just fixed it.

**Comment by stevanwilson** [comment]
hey did you commit the fix?

**Comment by stevanwilson** [comment]
You fix needs to be committed.

**Comment by Hydroplane72** [comment]
I did commit though. Check your data base numbers. Check and see if yard is equal to 1. That was the problem that needed to be fixed on my computer. Maybe my commit only affected the data base scheme and didn't affect the numbers within.

**Comment by Hydroplane72** [comment]
I can see that the insert statement within the script file insert is correct. The problem is that  when you look at the data base itself you will see that yard is showing as 1. I corrected this by deleting the yard row in the file and then making a new Yard. Another way to do this is to manually change the script file. 
![image](https://cloud.githubusercontent.com/assets/25423369/24225349/ff78d942-0f2d-11e7-9044-b5684baec3f9.png)

**Comment by stevanwilson** [comment]
I did what you said and it fixed it for me. Hopefully the newest version will fix everyone's file. Thanks!
